
CREATE TABLE Paciente (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Nome NVARCHAR(100) NOT NULL,
    Telefone NVARCHAR(20) NOT NULL,
    Sexo NVARCHAR(10) NOT NULL,
    Email NVARCHAR(100) NOT NULL
);
